# docker-compose.yml
version: '3'
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:master123@postgres:5432/programming-questionnaire-server
      NODE_ENV: development
      PORT: 8000
    ports:
      - '8000:8000'
    command:
      [sh, -c, 'npm run sync && npm run seeders:load && npm start']
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules

  postgres:
    image: postgres:alpine
    ports:
      - '35432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: master123
      POSTGRES_DB: programming-questionnaire-server
